apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gorush
  namespace: gorush
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gorush
        tier: frontend
    spec:
      containers:
      - image: dtable/gorush:1.11.3
        name: gorush
        args: ["-c", "/gorushconf/conf/config.yaml"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        volumeMounts:
          - name: p8-key-volume
            mountPath: /gorushconf/key
          - name: config-volume
            mountPath: /gorushconf/conf
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: GORUSH_STAT_ENGINE
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: stat.engine
        - name: GORUSH_STAT_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: stat.redis.host
      volumes:
        - name: p8-key-volume
          secret:
            secretName: k8key.p8
        - name: config-volume
          secret:
            secretName: config.yaml

